Adding Assignment A02 in branch A02
Ajay07Metamation/Training pull request #1
Opened 2023-07-25 03:45 UTC by Ajay07Metamation

2023-07-25 14:41 UTC, rajeevramanTMM requested changes

2023-07-25 14:50 UTC, Ajay07Metamation commented on Training/Program.cs
> +﻿int random = new Random ().Next (1, 101); //Variable to store random number generated
Ok sir. I will change and send it.

2023-07-25 14:51 UTC, Ajay07Metamation commented on Training/Program.cs
> +    else if (guess > random)
Ok sir. I will change and send it.

2023-07-25 14:51 UTC, Ajay07Metamation commented on Training/Program.cs
> +int ReadInt () { // To get valid input from user and convert to integer
Ok sir. I will change and send it.

2023-07-26 08:08 UTC, Ajay07Metamation commented on Training/Program.cs
> +    else if (guess > random)
I have done the changes mentioned.

2023-08-26 08:25 UTC, closed without merging