Completed T07
Ajay07Metamation/Training pull request #11
Opened 2023-08-11 11:12 UTC by Ajay07Metamation

2023-10-13 05:52 UTC, varalakshmi-imm requested changes
![image](https://github.com/Ajay07Metamation/Training/assets/75829713/aad16aa4-bed3-4ec7-9382-dbc4603ceb66)
Exclude .gitignore from your solution

2023-10-13 05:52 UTC, varalakshmi-imm commented on Training/Program.cs
> +OutputEncoding = new UnicodeEncoding ();
Leave a blank space after usings and then start the coding.

2023-10-13 05:52 UTC, varalakshmi-imm commented on Training/Program.cs
> +WriteLine ("\u2523" + String.Concat (Enumerable.Repeat ("\u2501\u2501\u2501\u2501\u2501\u252b", 8)));
This is repeated again later in the code. Refactor this to a method and call it say OuputHorizontalLine or OutputVerticalLine etc.

2023-10-13 05:52 UTC, varalakshmi-imm commented on Training/Program.cs
> +   Write ($"  {white[8]}  \u2503");
You could have used the same Enumerable.Repeat for this too

2023-10-13 05:52 UTC, varalakshmi-imm commented on Training/Program.cs
> +   WriteLine (String.Concat (Enumerable.Repeat ("\u2503     ", 9)));
Again this is repeated. Refactor

2023-10-13 05:52 UTC, varalakshmi-imm commented on Training/Program.cs
> +   Write ($"  {black[8]}  \u2503");
Same use Enumerable.Repeat

2023-10-13 05:52 UTC, varalakshmi-imm commented on Training/Program.cs
> +   Write ($"  {black[i]}  \u2503");
Same kind of loop used for white too. So Refactor for black and white to use same method.

2023-10-13 06:57 UTC, Ajay07Metamation commented on Training/Program.cs
> +   Write ($"  {black[i]}  \u2503");
All changes are done in the latest commit

2023-10-13 07:49 UTC, varalakshmi-imm requested changes
![image](https://github.com/Ajay07Metamation/Training/assets/75829713/36b2ab4f-fb29-46f5-a14e-c9646e05a735)
You haven't turned on the option for Documentation file. Just leave the XML path as empty

2023-10-13 07:49 UTC, varalakshmi-imm commented on Training/Program.cs
> +HorizontalVerticalLines ('V');
Name could be just DrawLines or OutputLines.

2023-10-13 07:49 UTC, varalakshmi-imm commented on Training/Program.cs
> +void HorizontalVerticalLines (char code) => WriteLine (code == 'H' ? "\u2523" + String.Concat (Enumerable.Repeat ("\u2501\u2501\u2501\u2501\u2501\u252b", 8)) :
Naming of parameter is not good. Maybe line or type.

2023-10-13 07:49 UTC, varalakshmi-imm commented on Training/Program.cs
> +Write ("\u2503");
This is repeated.

2023-10-13 07:49 UTC, varalakshmi-imm commented on Training/Program.cs
> +   for (int i = 0; i < 8; i++)
Instead for you could have used Enumerable.Repeat right?

2023-10-13 07:49 UTC, varalakshmi-imm commented on Training/Program.cs
> +void PrintCoins (string[] piece) {
Shouldn't it be named pieces?

2023-10-13 07:49 UTC, varalakshmi-imm commented on Training/Program.cs
> +                                            String.Concat (Enumerable.Repeat ("\u2503     ", 9)));
![image](https://github.com/Ajay07Metamation/Training/assets/75829713/4071a0f2-7a3c-44b4-9a8c-926d78f2eec4)
Split in a readable and meaningful way like the above.

2023-10-13 09:03 UTC, Ajay07Metamation commented on Training/Program.cs
> +   for (int i = 0; i < 8; i++)
Mam I have a doubt in this comment. Here I'm using for because I want to print the coins in the array using its index. Can we do that using Enumerable.Repeat mam?

2023-10-13 10:04 UTC, Ajay07Metamation commented on Training/Program.cs
> +                                            String.Concat (Enumerable.Repeat ("\u2503     ", 9)));
Mam I have made the all changes mentioned in the latest commit

2023-10-14 04:08 UTC, varalakshmi-imm requested changes

2023-10-14 04:08 UTC, varalakshmi-imm commented on Training/Training.csproj
> +    <GenerateDocumentationFile>True</GenerateDocumentationFile>
You have set this and the wrote summary XML too.
But have you checked the output xml of your program?

Only if you have the classic style Program.Main this xml comments will be written out. 
![image](https://github.com/Ajay07Metamation/Training/assets/75829713/77e1bcd7-0f32-45ea-8780-e912da6a6cd5)
Try this later. But for this assignment keep the current code as it is and reset the documentation option and convert the xml comments to normal // comments.

2023-10-14 04:08 UTC, varalakshmi-imm commented on Training/Program.cs
> +/// <param name="line">Horizontal (H) or vetrical (v) Grid</param>
Typo for vertical
![image](https://github.com/Ajay07Metamation/Training/assets/75829713/c38e93c9-e02b-4754-834f-100df96dab21)

2023-10-14 05:12 UTC, varalakshmi-imm commented on Training/Program.cs
> +   for (int i = 0; i < 8; i++)
You are right. I overlooked that.

2023-10-14 05:15 UTC, varalakshmi-imm requested changes

2023-10-14 05:15 UTC, varalakshmi-imm commented on Training/Program.cs
> +      for (int i = 0; i < 8; i++)
```suggestion
      foreach (var piece in pieces)

```
This will be more readable.

2023-10-14 05:15 UTC, varalakshmi-imm commented on Training/Program.cs
> +      Write (String.Concat (Enumerable.Repeat ($"  {pieces[8]}  \u2503", 8)));
Instead of having the pawn in the array could have  just used the unicode char for pawn.

2023-10-16 06:10 UTC, Ajay07Metamation commented on Training/Program.cs
> +      Write (String.Concat (Enumerable.Repeat ($"  {pieces[8]}  \u2503", 8)));
Mam here I have to print two colors of pawns. As I have given the printing of pawns inside the methods PrintCoins, I will not be able to print it using a single line. I should give conditions for color and then print the appropriate pawn. So, I have used array.

2023-10-16 06:13 UTC, Ajay07Metamation commented on Training/Program.cs
> +      for (int i = 0; i < 8; i++)
Mam I have used for because I have given the Unicode character for pawn in the last of the array. If I use a foreach loop it would also print the pawn. So I am using a for loop

2023-10-16 06:19 UTC, Ajay07Metamation commented on Training/Program.cs
> +      Write (String.Concat (Enumerable.Repeat ($"  {pieces[8]}  \u2503", 8)));
All changes mentioned are done in the latest commit mam

2023-10-16 06:34 UTC, varalakshmi-imm commented on Training/Program.cs
> +      for (int i = 0; i < 8; i++)
I suggested to keep the pawn separately and not part of this array.
Better have two methods PrintCoins and PrintPawns. That way you don't need to access the last element of the array.

2023-10-16 06:39 UTC, varalakshmi-imm requested changes

2023-10-16 06:39 UTC, varalakshmi-imm commented on Training/Program.cs
> +    if (type == 'P')
I suggested to keep the pawn separately and not part of this array.
Better have two methods PrintCoins and PrintPawns. That way you don't need to access the last element of the array.

2023-10-16 06:39 UTC, varalakshmi-imm commented on Training/Program.cs
> +        foreach (var piece in pieces)
This causes incorrect output.
![image](https://github.com/Ajay07Metamation/Training/assets/75829713/05160c36-ef4b-4d4b-aca1-8d772fbcf8e2)

Always compile and check the output before you push

2023-10-16 06:39 UTC, varalakshmi-imm commented on Training/Program.cs
> +// To print the coins</summary>
summary tag not removed.

2023-10-16 06:39 UTC, varalakshmi-imm commented on Training/Program.cs
> +// name="pieces" Indicates the colour of coins
```suggestion
// "pieces" Indicates the colour of coins

```
Only for XML comments can use param or such names make sense.

2023-10-16 06:39 UTC, varalakshmi-imm commented on Training/Program.cs
> +// To print the coins</summary>
```suggestion
// This prints the main coins on the chessboard</summary>

```
Write meaningful sentences

2023-10-16 06:39 UTC, varalakshmi-imm commented on Training/Program.cs
> +// Print Horizontal and vertical lines for grid
```suggestion
// Print horizontal and vertical lines for grid

```
Watch out for proper lower case upper case in a sentence

2023-10-16 09:43 UTC, Ajay07Metamation commented on Training/Program.cs
> +// Print Horizontal and vertical lines for grid
Mam all changes done in the latest commit

2023-10-16 09:51 UTC, varalakshmi-imm requested changes

2023-10-16 09:51 UTC, varalakshmi-imm commented on Training/Program.cs
> +void DrawLines (char line) => WriteLine (line == 'H' ? "\u2523" + String.Concat (Enumerable.Repeat ("\u2501\u2501\u2501\u2501\u2501\u252b", 8))
Could be 
![image](https://github.com/Ajay07Metamation/Training/assets/75829713/e87ddafc-14cf-4298-8f01-6df62b0c3a6b)

2023-10-16 09:51 UTC, varalakshmi-imm commented on Training/Program.cs
> +// "pieces" Indicates the colour of coins
```suggestion
// "pieces" - Indicates the main coins 

```

2023-10-16 09:51 UTC, varalakshmi-imm commented on Training/Program.cs
> +// Print horizontal and vertical lines for grid
```suggestion
// Prints horizontal and vertical lines for grid

```

2023-10-16 09:57 UTC, Ajay07Metamation commented on Training/Program.cs
> +// Print horizontal and vertical lines for grid
All changes done in the latest commit

2023-10-16 10:47 UTC, varalakshmi-imm approved these changes

2023-10-16 10:47 UTC, closed without merging