Completed T08
Ajay07Metamation/Training pull request #14
Opened 2023-08-18 10:04 UTC by Ajay07Metamation

2023-08-25 16:18 UTC, rajeevramanTMM commented on Training/Program.cs
> +for (int i = 1; i <= count; i++) {
Outer loop can be a while loop.

2023-08-25 16:18 UTC, rajeevramanTMM commented on Training/Program.cs
> +   for (int j = 1; j <= 10; j++) {
If a loop has one statement no need of curly braces.

2023-08-25 16:19 UTC, rajeevramanTMM commented on Training/Program.cs
> +      Console.WriteLine ($"{i}*{j} = {i * j}");
Printing was not as expected. Please refer the image in the assignment doc file.

2023-08-30 07:07 UTC, rajeevramanTMM requested changes

2023-08-30 07:07 UTC, rajeevramanTMM commented on Training/Program.cs
> +         Console.WriteLine ($"{i,2} * {j,2} = {i * j,-1}");
Why referring console again you have declared this has static in the using statement.

2023-08-31 10:51 UTC, Ajay07Metamation commented on Training/Program.cs
> +         Console.WriteLine ($"{i,2} * {j,2} = {i * j,-1}");
All changes done in latest commit

2023-08-31 14:33 UTC, rajeevramanTMM requested changes

2023-08-31 14:33 UTC, rajeevramanTMM commented on Training/Program.cs
> +   for (int i = 1; i <= count; i++) {
I have mentioned to change the outer loop to while in previous review comment can you please check.

2023-09-01 03:19 UTC, Ajay07Metamation commented on Training/Program.cs
> +   for (int i = 1; i <= count; i++) {
All changes done in latest commit

2023-09-04 04:26 UTC, closed without merging