Completed T11
Ajay07Metamation/Training pull request #15
Opened 2023-08-18 10:05 UTC by Ajay07Metamation

2023-08-26 07:08 UTC, rajeevramanTMM requested changes

2023-08-26 07:08 UTC, rajeevramanTMM commented on Training/Program.cs
> +while ((num.ToString ().Length) != 1) {
Store the tostring format in a variable and use it. Remove unnecessary brackets from while loop statement.

2023-08-26 07:08 UTC, rajeevramanTMM commented on Training/Program.cs
> +   foreach (char ch in elem) {
Remove brace for foreach loop only one statement.

2023-08-26 07:08 UTC, rajeevramanTMM commented on Training/Program.cs
> +   Array.Clear (elem, 0, elem.Length);
Do we need this array clearing I worked for me without this line ?

2023-08-31 12:09 UTC, Ajay07Metamation commented on Training/Program.cs
> +   Array.Clear (elem, 0, elem.Length);
All changes done in latest commit

2023-08-31 14:47 UTC, rajeevramanTMM requested changes

2023-08-31 14:47 UTC, rajeevramanTMM commented on Training/Program.cs
> +int.TryParse (Console.ReadLine (), out int num);
Fix this.
![image](https://github.com/Ajay07Metamation/Training/assets/94427955/1a2ae6ba-e80e-41e3-9a2c-083029d36dd1)

2023-09-01 03:34 UTC, Ajay07Metamation commented on Training/Program.cs
> +int.TryParse (Console.ReadLine (), out int num);
All changes and formatting done in T11

2023-09-04 04:28 UTC, closed without merging