Completed T13
Ajay07Metamation/Training pull request #18
Opened 2023-08-24 12:05 UTC by Ajay07Metamation

2023-08-26 07:21 UTC, rajeevramanTMM requested changes

2023-08-26 07:21 UTC, rajeevramanTMM commented on Training/Program.cs
> +String valid (string s) {
Use string data type not the class for variable and function return type..

2023-08-26 07:21 UTC, rajeevramanTMM commented on Training/Program.cs
> +      if (!s.Any (spl.Contains)) result += "Password should contain atleast 1 special character \n";
You have to show the special character to the user if not he cant create a password.

2023-08-26 07:21 UTC, rajeevramanTMM commented on Training/Program.cs
> +      if (!s.Any (char.IsDigit)) result += "Password should contain atleast 1 numerical \n";
Multiple times the same message is repeated can you clean up the code.

2023-08-26 07:21 UTC, rajeevramanTMM commented on Training/Program.cs
> +string pass = Console.ReadLine () ?? "";
Remove console key word

2023-08-26 07:21 UTC, rajeevramanTMM commented on Training/Program.cs
> +String valid (string s) {
Provide a valid function name with capital letter for eg: IsValid.

2023-08-31 12:14 UTC, Ajay07Metamation commented on Training/Program.cs
> +String valid (string s) {
All changes done in latest commit

2023-09-01 03:40 UTC, Ajay07Metamation commented on Training/Program.cs
> +      if (!s.Any (spl.Contains)) result += res + "Special character !@#$%^&*()-+ ";
All changes done in latest commit

2023-09-04 04:25 UTC, closed without merging