Done Assignment A02.1
Ajay07Metamation/Training pull request #2
Opened 2023-07-27 11:51 UTC by Ajay07Metamation

2023-07-27 15:35 UTC, rajeevramanTMM requested changes

2023-07-27 15:35 UTC, rajeevramanTMM commented on Training/Program.cs
> +int Lowlimit, Highlimit, Baselimit;
Use camel case for naming. Initialization can be done along with the declaration itself. Default value for int is zero no need to specify it.

2023-07-27 15:35 UTC, rajeevramanTMM commented on Training/Program.cs
> +   if (key is ConsoleKey.Y)
Multiple if else statement rewrite using a switch statement. This could help you in reading how does a switch statement works.

2023-07-31 02:58 UTC, Ajay07Metamation commented on Training/Program.cs
> +   if (key is ConsoleKey.Y)
I have done the mentioned changes

2023-07-31 05:38 UTC, rajeevramanTMM requested changes

2023-07-31 05:38 UTC, rajeevramanTMM commented on Training/Program.cs
> +int LowLimit = 0;
Use camel case conventions and you can re-write multiple variable declaration of same type in a single line.

2023-07-31 05:38 UTC, rajeevramanTMM commented on Training/Program.cs
>  Console.WriteLine ("Heyy computer I'm thinking of a number try to guess it ");
Print a valid message where the user needs to think of a number between 1 to 100 as per your code logic.
Try to print this message in different foreground color and use a single WriteLine method to print the message as a wrap text.

2023-07-31 05:38 UTC, rajeevramanTMM commented on Training/Program.cs
>     var key = Console.ReadKey ().Key;
No need of this variable use the readkey in the switch case itself. As you are using only one instance of this no need to save that to a variable.

2023-07-31 07:16 UTC, Ajay07Metamation commented on Training/Program.cs
>  Console.WriteLine ("Heyy computer I'm thinking of a number try to guess it ");
I have done the changes mentioned.

2023-07-31 07:44 UTC, rajeevramanTMM requested changes

2023-07-31 07:44 UTC, rajeevramanTMM commented on Training/Program.cs
> +Console.ForegroundColor = ConsoleColor.Cyan;
Rewrite using  C# static directive for console class and refactor your code accordingly.

2023-07-31 08:53 UTC, Ajay07Metamation commented on Training/Program.cs
> +Console.ForegroundColor = ConsoleColor.Cyan;
I have done the mentioned changes

2023-08-26 08:26 UTC, closed without merging