Completed T15
Ajay07Metamation/Training pull request #20
Opened 2023-08-25 07:20 UTC by Ajay07Metamation

2023-08-26 07:35 UTC, rajeevramanTMM requested changes

2023-08-26 07:35 UTC, rajeevramanTMM commented on Training/Program.cs
> +bool breakouter = false;
Rewrite using a function call.

2023-08-26 07:35 UTC, rajeevramanTMM commented on Training/Program.cs
> +String letter = ReadLine () ?? "";
Use string data type not class

2023-08-26 07:35 UTC, rajeevramanTMM commented on Training/Program.cs
> +   if (breakouter == true) break;
No need to check true explicitly.

2023-08-26 07:35 UTC, rajeevramanTMM commented on Training/Program.cs
> +if (breakouter == false) WriteLine ("It is an Isogram");
Handle this situtaion.
![image](https://github.com/Ajay07Metamation/Training/assets/94427955/656af44d-24ba-40c8-b922-6c8b7df6b44d)

2023-08-26 07:35 UTC, rajeevramanTMM commented on Training/Program.cs
> +// Using LINQ operator
Is this a reference code for testing the method if so please provide a naming and print it. This is printing two time has shown in the image above which is confusing.

2023-08-31 12:18 UTC, Ajay07Metamation commented on Training/Program.cs
> +// Using LINQ operator
All changes done in latest commit

2023-09-04 05:42 UTC, rajeevramanTMM requested changes

2023-09-04 05:42 UTC, rajeevramanTMM commented on Training/Program.cs
> +string IsIsogram(string s) {
The name IsIsogram represents a boolean return type but here you returning a string type. Please change the return type or the method name. Please leave a line in between a  method and a section of code and formatting to be applied.

2023-09-04 06:40 UTC, Ajay07Metamation commented on Training/Program.cs
> +string IsIsogram(string s) {
All changes and formatting done in latest commit

2023-09-04 07:10 UTC, rajeevramanTMM requested changes

2023-09-04 07:10 UTC, rajeevramanTMM commented on Training/Program.cs
> +if (letter.All (char.IsLetter) && letter.Length >= 1)
Can you please check the length condition first and use any operator instead of All. All will be checking the full string.

2023-09-04 07:54 UTC, closed without merging