Completed T16
Ajay07Metamation/Training pull request #21
Opened 2023-08-25 07:20 UTC by Ajay07Metamation

2023-08-26 07:43 UTC, rajeevramanTMM requested changes

2023-08-26 07:43 UTC, rajeevramanTMM commented on Training/Program.cs
> +using static System.Console;
Re-write using a function as mentioned in the assignment.

2023-08-26 07:43 UTC, rajeevramanTMM commented on Training/Program.cs
> +else Console.WriteLine ($"ABECEDARIAN WORD : {String.Concat (wordcheck)}");
Use string.join not concat method.

2023-08-26 07:43 UTC, rajeevramanTMM commented on Training/Program.cs
> +string word = Console.ReadLine () ?? "";
Remove unused console

2023-08-31 10:21 UTC, Ajay07Metamation commented on Training/Program.cs
> +string word = Console.ReadLine () ?? "";
All changes done in latest commit

2023-09-04 05:51 UTC, rajeevramanTMM requested changes

2023-09-04 05:51 UTC, rajeevramanTMM commented on Training/Program.cs
> +if (int.TryParse (ReadLine (), out int index)) {
No need brace in a single line statement.

2023-09-04 05:51 UTC, rajeevramanTMM commented on Training/Program.cs
> +void GetAbecedarian (int index) {
Please provide a line between the methods. The method input name can be "size" instead of index. You are using this int value to create an array. Use index naming in the for loop. The word array is initialized on both sides, which is not needed. Provide variables and methods of naming related to the context.

2023-09-04 05:51 UTC, rajeevramanTMM commented on Training/Program.cs
> +   var sortedword = words.Where (word => word == string.Join ("", word.OrderBy (c => c)));
Use camel case in this scenario. Format the code as well.

2023-09-04 07:27 UTC, Ajay07Metamation commented on Training/Program.cs
> +   var sortedword = words.Where (word => word == string.Join ("", word.OrderBy (c => c)));
All changes and formatting done in latest commit

2023-09-04 07:43 UTC, rajeevramanTMM requested changes

2023-09-04 07:43 UTC, rajeevramanTMM commented on Training/Program.cs
> +   var SortedWord = words.Where (word => word == string.Join ("", word.OrderBy (c => c)));
You can get the result in sorted word itself. Use FirstOrDefault instead of First.

2023-09-04 07:43 UTC, rajeevramanTMM commented on Training/Program.cs
> +   for (int index = 0; index < size; index++) {
For loop to be iterated till words.length not size. No need to initialize Words array on both the sides.

2023-09-04 08:55 UTC, Ajay07Metamation commented on Training/Program.cs
> +   for (int index = 0; index < size; index++) {
All changes done in latest commit

2023-09-04 09:02 UTC, Ajay07Metamation commented on Training/Program.cs
> +   for (int index = 0; index < size; index++) {
Changes done in recent commit

2023-09-04 09:09 UTC, closed without merging