Completed T17
Ajay07Metamation/Training pull request #22
Opened 2023-09-01 09:16 UTC by Ajay07Metamation

2023-09-04 11:47 UTC, MetaNaveen requested changes

2023-09-04 11:47 UTC, MetaNaveen commented on Training/Program.cs
> +   GetPermute (word, answer);
The method name implies that something should be returned. The name could have been "PrintPermutation ()".

Anyways, could you get array of permuted words as result of GetPermute() method and the print it?

2023-09-04 11:47 UTC, MetaNaveen commented on Training/Program.cs
> +void GetPermute (string word, string answer) {
We use an empty line before a Method definition as a coding style guideline.

2023-09-05 04:16 UTC, Ajay07Metamation commented on Training/Program.cs
> +void GetPermute (string word, string answer) {
All changes and formatting done in latest commit

2023-09-12 08:49 UTC, MetaNaveen commented
**Final Notes For Consideration:**

- Simplify using var on LHS or new () on RHS.
- It now says 'PrintPermute' but only computes the permutation to store it in the caller's List object. Name appropriately.

2023-09-12 08:49 UTC, closed without merging