Completed T18
Ajay07Metamation/Training pull request #23
Opened 2023-09-01 09:26 UTC by Ajay07Metamation

2023-09-04 11:54 UTC, MetaNaveen requested changes

2023-09-04 11:54 UTC, MetaNaveen commented on Training/Program.cs
> +      res += Math.Pow ((n % 10), exp);
Can you avoid inbuilt function Math.Pow()?

2023-09-04 11:54 UTC, MetaNaveen commented on Training/Program.cs
> +   GetAmstrong (num);
GetAmstrong() implies something is returned.
Can you make the method to return true if it is an Armstrong number.

By the way, it's Armstrong number, not Amstrong.

2023-09-04 11:54 UTC, MetaNaveen commented on Training/Program.cs
> +   WriteLine ($"It is {((res == num) ? "" : "not ")}an Armstrong Number");
You are comparing double against integer. Are you sure it's safe to compare double against integer?

2023-09-05 05:29 UTC, Ajay07Metamation commented on Training/Program.cs
> +   WriteLine ($"It is {((res == num) ? "" : "not ")}an Armstrong Number");
All changes and formatting done in T18

2023-09-12 09:05 UTC, MetaNaveen commented
**Final Notes For Consideration:**

- **return (res == num) ? true : false;** can be simplified into **return res == num;**

2023-09-12 09:05 UTC, closed without merging