Completed T18.1
Ajay07Metamation/Training pull request #24
Opened 2023-09-01 09:56 UTC by Ajay07Metamation

2023-09-04 11:58 UTC, MetaNaveen commented
Not able to run the program.
Kindly check if the program is running before submission!

2023-09-05 06:28 UTC, Ajay07Metamation commented
> Not able to run the program. Kindly check if the program is running before submission!

The program was asked to write in such a way that it should run from command prompt.

2023-09-05 06:28 UTC, Ajay07Metamation commented
Can you please check it again na?

2023-09-12 09:21 UTC, MetaNaveen requested changes

2023-09-12 09:21 UTC, MetaNaveen commented on Training/Program.cs
> +         while (check > 0) {
All the single digit positive integers are Armstrong numbers by nature. 
By adding certain logic, you could avoid computation for those digits as well as you could skip and start from appropriate value.

2023-09-12 09:21 UTC, MetaNaveen commented on Training/Program.cs
> +      while (count < index) {
It might be easier to follow, if you try to follow some uniformity when using operators in conditions.

**For example:** if you are using < in comparison often, try to follow the same pattern elsewhere. (you could change the code to: while (0 < check) or while (count > index)

2023-09-14 09:02 UTC, Ajay07Metamation commented on Training/Program.cs
> +      while (count < index) {
I have done the changes mentioned above in the latest commit

2023-09-22 15:20 UTC, MetaNaveen reviewed
Working fine.

Check the review and close the PR.

2023-09-22 15:20 UTC, MetaNaveen commented on Training/Program.cs
> +         return $"The {index}th Armstrong Number : {index}";
The suffix "th" is not correct in all context.

2023-09-25 04:40 UTC, Ajay07Metamation commented on Training/Program.cs
> +         return $"The {index}th Armstrong Number : {index}";
Changes done. Closing the PR

2023-09-25 04:40 UTC, closed without merging