Completed T19
Ajay07Metamation/Training pull request #25
Opened 2023-09-01 10:09 UTC by Ajay07Metamation

2023-09-05 06:47 UTC, Ajay07Metamation commented on Training/Program.cs
> +double GetFactorial (int n) {
I have given the return type as double because if we give a number more than 30 its factorial becomes large so that it cannot be stored in a int. It returns a negative value or 0. So I have given double as a return type.

2023-09-12 09:39 UTC, MetaNaveen requested changes

2023-09-12 09:39 UTC, MetaNaveen commented on Training/Program.cs
> +double GetFactorial (int n) {
You could use other better datatypes in such case. Since we are dealing with integrals, you could read/use integral datatype from [link](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types).

2023-09-14 09:11 UTC, Ajay07Metamation commented on Training/Program.cs
> +double GetFactorial (int n) {
I have done the changes mentioned in the latest commit

2023-09-22 15:15 UTC, MetaNaveen commented on Training/Program.cs
> +if (ulong.TryParse (ReadLine (), out ulong num) && 0 <= num)
second condition is unnecessary.

2023-09-25 04:46 UTC, Ajay07Metamation commented on Training/Program.cs
> +if (ulong.TryParse (ReadLine (), out ulong num) && 0 <= num)
Changes done and closing the PR.

2023-09-25 04:46 UTC, closed without merging