Completed T20
Ajay07Metamation/Training pull request #26
Opened 2023-09-01 10:38 UTC by Ajay07Metamation

2023-09-05 10:43 UTC, Ajay07Metamation commented on Training/Program.cs
> +   string numword = num.ToString ();
All changes done in latest commit

2023-09-12 10:15 UTC, MetaNaveen requested changes

2023-09-12 10:15 UTC, MetaNaveen commented on Training/Program.cs
> +if (double.TryParse (ReadLine (), out double num)) {
Kindly change the code as in this order.

- Check if the user input is of type decimal.
- Split the user input by '.'
- Convert the result elements to integer.
- Create a method to return List<int>/int[] for a given int (eg: GetIntArrFromInt(int n) {...})
- get int[] for first part (integral) of the split.
- get int[] for second part (fractional) of the split, if any
- print the arrays.

I don't want to see **.ToString()** anywhere in the code.

2023-09-14 11:53 UTC, Ajay07Metamation commented on Training/Program.cs
> +if (double.TryParse (ReadLine (), out double num)) {
Changes done in latest commit

2023-09-22 15:24 UTC, MetaNaveen reviewed
Fix and close the PR by yourself.

2023-09-22 15:24 UTC, MetaNaveen commented on Training/Program.cs
> +void GetFracListFromFrac (string[] decimalArr) {
Since array is used. If the result is not same as the original length, prepend 0s. So that even for input 00.00 the output should be 00.00.

All except the above working fine as defined.

Fix and close the PR by yourself.

2023-09-25 05:23 UTC, Ajay07Metamation commented on Training/Program.cs
> +void GetFracListFromFrac (string[] decimalArr) {
Changes done and closing the PR

2023-09-25 07:04 UTC, MetaNaveen commented on Training/Program.cs
> +void GetIntListFromInt (string[] decimalArr) {
I hope that I have mentioned not to print in the method when you are using method name starting with "Get". Kindly correct it as well.

2023-09-25 07:13 UTC, MetaNaveen commented on Training/Program.cs
> +void GetFracListFromFrac (string[] decimalArr) {
Output format is inconsistant. (as per question, Print each element with a space).
Output for 10.001 is wrong.

2023-09-25 11:52 UTC, Ajay07Metamation commented on Training/Program.cs
> +void GetIntListFromInt (string[] decimalArr) {
Changes done in latest commit

2023-09-25 12:51 UTC, MetaNaveen requested changes

2023-09-25 12:51 UTC, MetaNaveen commented on Training/Program.cs
> +void PrinttFracListFromFrac (string[] decimalArr) {
It's "Print" not "Printt". Having typo for a single change in a review request is not acceptable. Kindly update it.

2023-09-25 12:51 UTC, MetaNaveen commented on Training/Program.cs
> +void PrintIntListFromInt (string[] decimalArr) {
You could pass just the required string, instead of sending string array itself.

2023-09-25 12:51 UTC, MetaNaveen commented on Training/Program.cs
> +   if (decimalNum.Contains (".")) {
For character, use single quote.

2023-09-25 12:51 UTC, MetaNaveen commented on Training/Program.cs
> +   if (fractionalNum == 0) {
Repetition of similar code block could be avoided and Separate code block for handling the value '0' is an overkill.

2023-09-26 11:02 UTC, Ajay07Metamation commented on Training/Program.cs
> +   if (fractionalNum == 0) {
Changes done in latest commit

2023-09-26 11:10 UTC, MetaNaveen commented on Training/Program.cs
> +   int fracLength = fractionalNum.ToString ().Length;
This line could be removed.

2023-09-26 11:11 UTC, MetaNaveen reviewed
Final Notes.

2023-09-26 11:11 UTC, MetaNaveen commented on Training/Program.cs
> +   int fracLength = fractionalNum.ToString ().Length;
This line could be removed.

2023-09-28 10:03 UTC, Ajay07Metamation commented on Training/Program.cs
> +   int fracLength = fractionalNum.ToString ().Length;
Changes done

2023-10-04 04:43 UTC, Ajay07Metamation commented on Training/Program.cs
> +      WriteLine ();
Sorry about the mistake. Hereafter this won't happen. I have checked the program and reassigned it now.

2023-10-04 06:56 UTC, closed without merging