Completed T21
Ajay07Metamation/Training pull request #27
Opened 2023-09-01 10:49 UTC by Ajay07Metamation

2023-09-04 12:17 UTC, MetaNaveen requested changes

2023-09-04 12:17 UTC, MetaNaveen commented on Training/Program.cs
> +void GetSwap (int a, int b) {
Name could have been PrintSwap()

2023-09-05 10:47 UTC, Ajay07Metamation commented on Training/Program.cs
> +void GetSwap (int a, int b) {
All changes mentioned are done in latest commit

2023-09-12 10:16 UTC, closed without merging

2023-09-12 10:16 UTC, MetaNaveen commented
Working fine.