Completed T22
Ajay07Metamation/Training pull request #28
Opened 2023-09-01 11:17 UTC by Ajay07Metamation

2023-09-04 12:25 UTC, MetaNaveen requested changes

2023-09-04 12:25 UTC, MetaNaveen commented on Training/Program.cs
> +      WriteLine ($"Enter Valid Index between 0 and {numLength}");
Range specified in the error is incorrect.

![image](https://github.com/Ajay07Metamation/Training/assets/16486802/e61f1e07-34d5-46ca-890c-baf2c38547dc)

2023-09-04 12:25 UTC, MetaNaveen commented on Training/Program.cs
> +   int numLength = num.ToString ().Length;
You could have converted the string to array here and make use of it in the else block. It avoids the duplication and keeps the code concise.

2023-09-05 10:54 UTC, Ajay07Metamation commented on Training/Program.cs
> +   int numLength = num.ToString ().Length;
All changes mentioned are done in the latest commit

2023-09-12 10:22 UTC, MetaNaveen approved these changes

2023-09-12 10:23 UTC, closed without merging