Completed T23
Ajay07Metamation/Training pull request #29
Opened 2023-09-20 12:10 UTC by Ajay07Metamation

2023-09-21 04:47 UTC, Ajay07Metamation commented
Added XML comments

2023-09-22 14:19 UTC, MetaNaveen requested changes

2023-09-22 14:19 UTC, MetaNaveen commented on Training/Program.cs
> +                    .Select (x => new { letter = x.First (), lettercount = x.Count () })
If you could use tuple here instead of class object of anonymous type, you could return the result directly.

2023-09-22 14:19 UTC, MetaNaveen commented on Training/Program.cs
> +(char Letter, int Lettercount) GetWinner (string vote) {
Variable naming is inconsistent. For tuple items, you could either use camelCase or PythonCase. But make sure you use the same naming style everywhere else in the code.

2023-09-22 14:19 UTC, MetaNaveen commented on Training/Program.cs
> +///<summary>GetWinner : Returns the winner having highest number of votes</summary>
If summary is of multiple lines. Use like

**&lt;summary&gt;...
...&lt;/summary&gt;**

2023-09-22 14:19 UTC, MetaNaveen commented on Training/Program.cs
> +   var result = vote.GroupBy (x => x)
Using GroupBy () is great and appreciable. 
But do think it is performant? or any other solution that is much performant that this?

2023-09-22 14:19 UTC, MetaNaveen commented on Training/Program.cs
> +string vote = ReadLine ().ToLower ().Replace (" ", "");
You could use .Trim() for the same.

2023-09-22 14:19 UTC, MetaNaveen commented on Training/Program.cs
> +///<summary>VOTING CONTEST</summary>
Usage of summary is not required here.

2023-09-25 06:28 UTC, Ajay07Metamation commented on Training/Program.cs
> +string vote = ReadLine ().ToLower ().Replace (" ", "");
I have used "replace" to remove any spaces given inbetween the string but "trim" only removes the leading and trailing spaces

2023-09-25 06:54 UTC, MetaNaveen commented on Training/Program.cs
> +string vote = ReadLine ().ToLower ().Replace (" ", "");
To avoid confusion on undefined specification of the Problem statement, kindly remove both the Trim and Replace methods before submission. Kindly check with mentors before coding to avoid confusions.

2023-09-25 10:04 UTC, Ajay07Metamation commented on Training/Program.cs
> +///<summary>VOTING CONTEST</summary>
changes made in latest commit

2023-09-25 12:03 UTC, MetaNaveen requested changes

2023-10-09 05:42 UTC, MetaNaveen reviewed
Close the PR after fixing.

2023-10-09 05:42 UTC, MetaNaveen commented on Training/Program.cs
> +///<summary>GetWinner2 : Returns the winner having highest number of votes
// and /// should be followed by a space.

2023-10-09 05:42 UTC, MetaNaveen commented on Training/Program.cs
> +      if (list.Any (x => x.Item1 == vote[i])){
Computationally costly. You could have used just the .FindIndex(), without using .Any(), to complete the task.

2023-10-09 05:42 UTC, MetaNaveen commented on Training/Program.cs
> +(char Letter, int LetterCount) GetWinner (string vote) => vote.GroupBy (x => x)
The definition part could be put in the next line for better code readability.

2023-10-09 07:21 UTC, Ajay07Metamation commented on Training/Program.cs
> +(char Letter, int LetterCount) GetWinner (string vote) => vote.GroupBy (x => x)
All changes mentioned are done. Closing the PR

2023-10-09 09:12 UTC, closed without merging