Assignment A03 completed
Ajay07Metamation/Training pull request #3
Opened 2023-08-01 11:13 UTC by Ajay07Metamation

2023-08-30 09:04 UTC, rajeevramanTMM requested changes

2023-08-30 09:04 UTC, rajeevramanTMM commented on Training/Program.cs
> +string[] words = File.ReadAllLines ("D:\\OneDrive - Trumpf Metamation Pvt Ltd\\Desktop\\ASSIGNMENTS\\words.txt");
Your program crashes if the mentioned file does not exists.

2023-08-30 09:04 UTC, rajeevramanTMM commented on Training/Program.cs
> +   Console.WriteLine ($"{data.score,4} {data.word}");
Remove unused console.

2023-08-30 09:04 UTC, rajeevramanTMM commented on Training/Program.cs
> +bool isValid (string word) => word.Length >= 4 && word.Contains (letters[0]) && word.All (letters.Contains);
Provide method name in capital and leave one line space in between.

2023-08-31 10:43 UTC, Ajay07Metamation commented on Training/Program.cs
> +bool isValid (string word) => word.Length >= 4 && word.Contains (letters[0]) && word.All (letters.Contains);
All changes done in the latest commit

2023-08-31 13:16 UTC, closed without merging