T26 - LIST<T>
Ajay07Metamation/Training pull request #32
Opened 2023-10-04 11:20 UTC by Ajay07Metamation

2023-10-11 06:01 UTC, priyarathna commented on Training/Program.cs
> +      for (int i = 0; i < count; i++) {
Can be re-written as: Console.Write (string.Join (' ', arrayList))

2023-10-12 04:01 UTC, Ajay07Metamation commented on Training/Program.cs
> +      for (int i = 0; i < count; i++) {
All changes done in the latest commit

2023-10-13 09:12 UTC, priyarathna commented on Training/Program.cs
> +   /// <summary>Method Add to add an element in the list at the end</summary>
Update the comment lines.

2023-10-13 09:12 UTC, priyarathna commented on Training/Program.cs
> +   T[] marrayList;
Should be marrayList => mArrayList. Apply it wherever necessary.

2023-10-13 09:12 UTC, priyarathna commented on Training/Program.cs
> +      if (Array.IndexOf (marrayList, a) == -1) throw new InvalidOperationException ();
Array.IndexOf is used twice. Store it in a local variable and use that for the next time.

2023-10-13 09:12 UTC, priyarathna commented on Training/Program.cs
> +      for (int i = 0; i < mcount; i++) {
Flower-brace is not needed for single statements.

2023-10-13 09:12 UTC, priyarathna commented on Training/Program.cs
> +list.Add (5);
If I insert a test case: list.Remove (3) in line 11, the program gets crashed.

2023-10-16 11:17 UTC, Ajay07Metamation commented on Training/Program.cs
> +list.Add (5);
Done all changes in the latest commit

2023-10-17 05:09 UTC, priyarathna requested changes

2023-10-17 05:09 UTC, priyarathna commented on Training/Program.cs
> +      list.Remove (3);
Replace this as line.Remove (4). Program gets crashed.

2023-10-17 05:09 UTC, priyarathna commented on Training/Program.cs
> +      Array.Clear (mArrayList, 0, mCount - 1);
'Clear' should clear the entire list right? But it's working as expected.

2023-10-17 05:09 UTC, priyarathna commented on Training/Program.cs
> +      list.RemoveAt (2);
Replace this line as: list.RemoveAt (7). Program gets crashed.

2023-10-31 04:53 UTC, priyarathna requested changes

2023-10-31 04:53 UTC, priyarathna commented on Training/Program.cs
> +      if (elementPositon != mCount - 1)
This is not needed. Please check.

2023-10-31 04:53 UTC, priyarathna commented on Training/Program.cs
> +      if (index != mCount)
When this condition will be false?

2023-10-31 08:34 UTC, priyarathna approved these changes

2023-10-31 08:34 UTC, closed without merging