T27 - STACK<T>
Ajay07Metamation/Training pull request #33
Opened 2023-10-04 11:25 UTC by Ajay07Metamation

2023-10-16 11:26 UTC, Ajay07Metamation commented
All changes done in the latest commit

2023-10-20 04:54 UTC, priyarathna requested changes

2023-10-20 04:54 UTC, priyarathna commented on Training/Program.cs
> +   private T[] mArrayStack;
No need of 'private' explicitly. And private fields should be at the end of the program.

2023-10-20 04:54 UTC, priyarathna commented on Training/Program.cs
> +// To create a Stack using array as underlying structure
This comments is not understandable.

2023-10-20 04:54 UTC, priyarathna commented on Training/Program.cs
> +      for (int i = 0; i < mCount; i++) { Write (mArrayStack[i] + " "); }
Flower-brace is not needed for single statements.

2023-10-20 04:54 UTC, priyarathna commented on Training/Program.cs
> +      Write ("Popped element : ");
Remove Write/WriteLine in Pop/Peek. Use 'Display' for displaying the stack.

2023-10-31 04:42 UTC, priyarathna requested changes

2023-10-31 04:42 UTC, priyarathna commented on Training/Program.cs
> +// Test case
Comment is not relevant.

2023-10-31 04:42 UTC, priyarathna commented on Training/Program.cs
> +/// <summary>Represents a variable size last in first out collection of instances of same specified type</summary>
Comment is not relevant.

2023-10-31 04:42 UTC, priyarathna commented on Training/Program.cs
> +   /// <summary>Print the last element inserted at the top of the stack</summary>
Comment is not relevant.

2023-10-31 10:47 UTC, priyarathna requested changes

2023-10-31 10:47 UTC, priyarathna commented on Training/Program.cs
> +   #region Property --------------------------------------------
Not 'Property'. Change it to 'Properties'.

2023-11-01 05:30 UTC, priyarathna approved these changes

2023-11-01 05:30 UTC, closed without merging