A14.2 : Test case for Wordle
Ajay07Metamation/Training pull request #48
Opened 2024-02-08 11:36 UTC by Ajay07Metamation

2024-02-09 04:34 UTC, varalakshmi-imm requested changes

2024-02-09 04:34 UTC, varalakshmi-imm commented on Program.cs
> +      public Wordle (StreamWriter writer) {
This should be an additional constructor. You should not change the original class for which you are adding tests. I should be able to run wordle irrespective of tests.

2024-02-09 04:34 UTC, varalakshmi-imm commented on Program.cs
> +      public bool CheckTextFilesEqual (string f1, string f2) {
This method need not be part of wordle class. You could have added it in Test project itself.

2024-02-09 04:34 UTC, varalakshmi-imm commented on Program.cs
> +               PutToFile ($"You found the word in {mY} tries", Green);
You are calling PutToFile in Put itself. So why do you need to call here separately?
Moreover the string messages are repeated.

2024-02-09 04:34 UTC, varalakshmi-imm commented on Program.cs
> +         //ReadKey ();
Why is this commented out?

2024-02-09 04:34 UTC, varalakshmi-imm commented on Program.cs
> +            Gray or White or Yellow => $" {data} ",
```suggestion
            _ => $" {data} ",

```

2024-02-09 04:34 UTC, varalakshmi-imm commented on Program.cs
> +            _ => "",
Not required

2024-02-09 04:34 UTC, varalakshmi-imm commented on TestWordle/UnitTest1.cs
> +      // Test the backspace key input
```suggestion
      // Tests the backspace key input

```
Change such comments everywhere

2024-02-09 04:34 UTC, varalakshmi-imm commented on TestWordle/UnitTest1.cs
> +         mGame.SelectWord ();
Why is this required?
You are setting a secret word anyways.

2024-02-09 04:34 UTC, varalakshmi-imm commented on TestWordle/UnitTest1.cs
> +      public void TestFiles (string[] mInput, ConsoleKey Key, string mRefFile) {
```suggestion
      public void TestFiles (string[] input, ConsoleKey key, string refFile) {

```
Parameters should not have m prefix and they should start in lowercase.

2024-02-09 04:34 UTC, varalakshmi-imm commented on TestWordle/UnitTest1.cs
> +         var mTestFile = "C:/etc/TestFile.txt";
```suggestion
         var testFile = "C:/etc/TestFile.txt";

```
Local variable too should not have m prefix only member variables.

2024-02-09 04:34 UTC, varalakshmi-imm commented on TestWordle/UnitTest1.cs
> +         writer.Close ();
Always use Using, so that the dispose will be called as sometimes we forget to call close.

2024-02-12 05:08 UTC, varalakshmi-imm requested changes
Not able to run Wordle application separately. 
Adding tests should not break the application's workflow.

2024-02-12 05:37 UTC, varalakshmi-imm requested changes
Exception thrown if I run wordle and enter a valid word like "HELLO"
![image](https://github.com/Ajay07Metamation/Training/assets/75829713/acad72c8-b55f-4362-867c-e857fde5e19d)

2024-02-12 06:59 UTC, varalakshmi-imm requested changes

2024-02-12 06:59 UTC, varalakshmi-imm commented on TestWordle/UnitTest1.cs
> +            var file1 = File.ReadAllText (f1).Replace ("\r\n", "\n");
```suggestion
            var file1 = File.ReadAllText (f1);

```
Isn't this enough?

2024-02-12 07:07 UTC, Ajay07Metamation commented on TestWordle/UnitTest1.cs
> +            var file1 = File.ReadAllText (f1).Replace ("\r\n", "\n");
It works but sometimes it opens winMerge even though the files are same.winMerge tells that the carraige is different but both files are identical.

2024-02-12 07:24 UTC, varalakshmi-imm commented on TestWordle/UnitTest1.cs
> +            var file1 = File.ReadAllText (f1).Replace ("\r\n", "\n");
Always replacing \r\n with \n. So this doesn't make sense to me if the reference files are also created from the test initially.

2024-02-12 07:26 UTC, varalakshmi-imm approved these changes

2024-02-12 07:26 UTC, closed without merging