Completed T02
Ajay07Metamation/Training pull request #6
Opened 2023-08-09 11:34 UTC by Ajay07Metamation

2023-08-25 14:08 UTC, rajeevramanTMM requested changes

2023-08-30 08:50 UTC, rajeevramanTMM commented
Apply changes based on the discussion.

2023-08-31 10:11 UTC, Ajay07Metamation commented on Training/Program.cs
> +void NumtoRoman (int num) {
Changes done in the latest commit

2023-09-04 05:52 UTC, rajeevramanTMM commented on Training/Program.cs
> +void NumtoRoman (int num) {
Fix this error,
![image](https://github.com/Ajay07Metamation/Training/assets/94427955/1703511e-ad71-401e-b12f-c217f1fa49f7)

2023-09-04 06:27 UTC, Ajay07Metamation commented on Training/Program.cs
> +void NumtoRoman (int num) {
Changes and formatting done in latest commit

2023-10-13 09:09 UTC, varalakshmi-imm requested changes

2023-10-13 09:09 UTC, varalakshmi-imm commented on Training/Program.cs
> +      if (numlength == 1) {
Whenever you have this kind of multiple if else if then should use switch.
But this code could be simplified without using switch too. 
for eg: numlength == 3, then divident = 100 and if 4 then 1000. So think of simplifying this based on numlength and divident value.

2023-10-13 09:09 UTC, varalakshmi-imm commented on Training/Program.cs
> +   while (num > 0)
Having brackets will make code clear.

2023-10-13 09:09 UTC, varalakshmi-imm commented on Training/Program.cs
> +   if (num == 0) WriteLine ("No Roman Number representation for 0");
if (num == 0) it should return after printing the message right?

2023-10-13 09:09 UTC, varalakshmi-imm commented on Training/Program.cs
> +            num = num - number[i];
Should use -= here like previous line +=.
Look for the intellisense underlines and fix them.
![image](https://github.com/Ajay07Metamation/Training/assets/75829713/bcad58b6-ef7d-4f70-b403-996515cb79a3)

2023-10-13 09:09 UTC, varalakshmi-imm commented on Training/Program.cs
> +      switch (ReadKey ().Key) {
Do you really need this switch case? Just a if else check could do the same job.

2023-10-13 12:07 UTC, Ajay07Metamation commented on Training/Program.cs
> +      switch (ReadKey ().Key) {
All changes mentioned are done in the latest commit mam.

2023-10-14 05:00 UTC, varalakshmi-imm requested changes
- Write // comments for methods.
- .gitignore is not excluded

2023-10-14 05:00 UTC, varalakshmi-imm commented on Training/Program.cs
> +   string[] roman = { "I", "IV", "V", "IX", "X", "XL", "L", "XC", "C", "CD", "D", "CM", "M" };
```suggestion
   string[] romans = { "I", "IV", "V", "IX", "X", "XL", "L", "XC", "C", "CD", "D", "CM", "M" };

```

2023-10-14 05:00 UTC, varalakshmi-imm commented on Training/Program.cs
> +   int[] number = { 1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000 };
```suggestion
   int[] numbers = { 1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000 };

```

2023-10-16 05:29 UTC, Ajay07Metamation commented on Training/Program.cs
> +   int[] number = { 1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000 };
All changes mentioned are done in the latest commit mam.

2023-10-16 05:47 UTC, varalakshmi-imm requested changes

2023-10-16 05:47 UTC, varalakshmi-imm commented on Training/Program.cs
> +﻿//Numbers to words or roman numbers
```suggestion
﻿// Numbers to words or roman numbers
```
Leave a space after //

2023-10-16 05:47 UTC, varalakshmi-imm commented on Training/Program.cs
> +    if (!int.TryParse (ReadLine (), out int num) && num >= 0) {
```suggestion
    if (!int.TryParse (ReadLine (), out int num) || num < 0) {

```
You negated the if but not the &&
If you enter the number as -1, your program hangs now.

2023-10-16 05:47 UTC, varalakshmi-imm commented on Training/Program.cs
> +        WriteLine ();
This should be above the line if (choice == ConsoleKey.W) {
        WriteLine ();
![image](https://github.com/Ajay07Metamation/Training/assets/75829713/cda6d8ec-b861-407f-b7aa-0f1386cf6a02)

2023-10-16 05:47 UTC, varalakshmi-imm commented on Training/Program.cs
> +    Dictionary<int, string> numtowords = new () {
```suggestion
    Dictionary<int, string> words = new () {

```

2023-10-16 07:04 UTC, Ajay07Metamation commented on Training/Program.cs
> +    Dictionary<int, string> numtowords = new () {
All changes are done in the latest commit mam

2023-10-16 07:15 UTC, varalakshmi-imm requested changes
If I enter 10000, the output for Roman conversion is MMMMMMMMMM which is not right.
![image](https://github.com/Ajay07Metamation/Training/assets/75829713/f83487b2-c5c9-4471-94d0-6b2ea8da8b93)
So restrict it to 3999 for both words and romans

2023-10-16 07:27 UTC, Ajay07Metamation commented
Done changes

2023-10-16 07:38 UTC, varalakshmi-imm requested changes

2023-10-16 07:38 UTC, varalakshmi-imm commented on Training/Program.cs
> +            divisor = 1;
```suggestion
           else if (numlength == 2 && num > 20) divisor = 1;

```
Could be in single line

2023-10-16 07:38 UTC, varalakshmi-imm commented on Training/Program.cs
> +            divisor = (int)Math.Pow (10, numlength - 1);
```suggestion
           else divisor = (int)Math.Pow (10, numlength - 1);

```
Could be in single line

2023-10-16 07:38 UTC, varalakshmi-imm commented on Training/Program.cs
> +        result += (quo.ToString ().Length == 2 && quo > 20 ? words[quo - (quo % 10)] + " " + words[quo % 10] : words[quo])
See if you can split each plus part in this line into meaningful variables and finally merge into one.  
Also quo % 10 is done twice in this statement. Could have stored in a variable and accessed it.

2023-10-16 08:43 UTC, Ajay07Metamation commented on Training/Program.cs
> +        result += (quo.ToString ().Length == 2 && quo > 20 ? words[quo - (quo % 10)] + " " + words[quo % 10] : words[quo])
All changes done in the latest commit mam

2023-10-16 09:03 UTC, varalakshmi-imm requested changes

2023-10-16 09:03 UTC, varalakshmi-imm commented on Training/Program.cs
> +        var formattedQuo = quo.ToString ().Length == 2 && quo > 20 ? words[quo - unitDigit] + " " + words[unitDigit] : words[quo];
Not so good name formattedQuo.
But I too can't think of any suggestions.
So let it be.

2023-10-16 09:11 UTC, Ajay07Metamation commented on Training/Program.cs
> +        var formattedQuo = quo.ToString ().Length == 2 && quo > 20 ? words[quo - unitDigit] + " " + words[unitDigit] : words[quo];
All changes done mam

2023-10-16 09:18 UTC, varalakshmi-imm requested changes

2023-10-16 09:18 UTC, varalakshmi-imm commented on Training/Program.cs
> +    Write ("Enter a Number between 0 and 3999 : ");
Still haven't formatted this program.
Click Edit > Advanced > Format Document.
![image](https://github.com/Ajay07Metamation/Training/assets/75829713/0c71446b-5768-4758-a592-494230bd3b7c)

2023-10-16 09:25 UTC, Ajay07Metamation commented on Training/Program.cs
> +    Write ("Enter a Number between 0 and 3999 : ");
Mam I have done it again and pushed it mam

2023-10-16 09:35 UTC, varalakshmi-imm approved these changes

2023-10-16 09:36 UTC, varalakshmi-imm approved these changes

2023-10-16 09:36 UTC, varalakshmi-imm commented on Training/Program.cs
> +      var formattedQuo = quo.ToString ().Length == 2 && quo > 20 ? words[quo - unitDigit] + " " + words[unitDigit] : words[quo];
@Ajay07Metamation This has become long line after formatting.
Need to watch such lines after formatting.

2023-10-16 09:36 UTC, closed without merging