Completed t04
Ajay07Metamation/Training pull request #8
Opened 2023-08-09 11:34 UTC by Ajay07Metamation

2023-08-25 15:59 UTC, rajeevramanTMM requested changes

2023-08-25 15:59 UTC, rajeevramanTMM commented on Training/Program.cs
> +   int.TryParse (Console.ReadLine (), out int num1);
Remove unused console methods and using statements.

2023-08-25 15:59 UTC, rajeevramanTMM commented on Training/Program.cs
> +int lcm (int num1, int num2) {
Provide a valid method name and rewrite this expression using lambda operator.

2023-08-25 15:59 UTC, rajeevramanTMM commented on Training/Program.cs
> +int gcd (int num1, int num2) {
Valid function name

2023-08-25 15:59 UTC, rajeevramanTMM commented on Training/Program.cs
> +   int gcd = 0;
Fix this negative scenario exception.
![image](https://github.com/Ajay07Metamation/Training/assets/94427955/f09366e0-4182-4cb0-9c36-daf61fd7f468)

2023-08-30 05:04 UTC, rajeevramanTMM commented on Training/Program.cs
> +   int gcd = 0;
Please fix this error.
![image](https://github.com/Ajay07Metamation/Training/assets/94427955/afd9ac8e-0e43-4797-bc80-6fa97993dd83)

2023-08-31 11:19 UTC, Ajay07Metamation commented on Training/Program.cs
> +   int gcd = 0;
All changes done in latest commit

2023-08-31 13:43 UTC, closed without merging